/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    
    {
      type: 'category',
      label: 'Sails.js Tutorial',
      items: [
        { type: 'doc', id: 'sailsjs-tutorial/index' },
        { type: 'doc', id: 'sailsjs-tutorial/intro' },
        { type: 'doc', id: 'sailsjs-tutorial/requisites' },
        { type: 'doc', id: 'sailsjs-tutorial/installation' },
        { type: 'doc', id: 'sailsjs-tutorial/hello-world' },
      ],
    }
  ],
   
};
